--THIS WILL CREATE AN EMPLOYEE TABLE
CREATE TABLE EMPLOYEE(
 EMPLOYEE_ID INTEGER PRIMARY KEY, 
 EMPLOYEE_FIRSTNAME, VARCHAR(30),
 EMPLOYEE_LASTNAME, VARCHAR(30),
 DEPARTMENT_ID INTEGER  
 SALARY INTEGER,
 EMP_EMAIL, VARCHAR(30)
 
 CREATE SEQUENCE EMPLOYEESEQ;
 )
 
 CREATE TABLE DEPARTMENT(
 DEPARTMENT_ID INTEGER PRIMARY KEY,
 DEPARTMENT_NAME INTEGER VARCHAR(30),
 CREATE SEQUENCE DEPARTMENTSEQ;
 )
/